### ISSUE TITLE
Bug: SSLError

### ISSUE THREAD

**Issue by forchannot** [nonebot/nonebot2#1004]
**描述问题：**

莫名出现这个错误，不知道会影响啥

**如何复现？**

运行一段时间就会出现一次

**期望的结果**

正常

**环境信息：**

 - OS: [windows server2019]
 - Python Version: [3.9]
 - Nonebot Version: [2.0.0b2]

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [最新]

**截图或日志**

 [ERROR] apscheduler | Job "fetch_and_send (trigger: interval[0:00:03], next run at: 2022-05-23 13:22:09 CST)" raised an exception
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\nonebot\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot_bison\scheduler.py", line 62, in fetch_and_send
    to_send = await platform_manager[target_type].fetch_new_post(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot_bison\platform\platform.py", line 223, in fetch_new_post
    post_list = await self.get_sub_list(target)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot_bison\platform\weibo.py", line 47, in get_sub_list
    res = await client.get(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_client.py", line 1729, in get
    return await self.request(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 72, in start_tls
    raise exc
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpcore\backends\asyncio.py", line 63, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)

**Comment by mnixry** [comment]
这个问题和NoneBot无关，是插件 https://github.com/felinae98/nonebot-bison 的问题。

**Comment by forchannot** [comment]
> 这个问题和NoneBot无关，是插件 https://github.com/felinae98/nonebot-bison 的问题。

ok
