### ISSUE TITLE
Bug: 多个bot.send_private_msg会抛出异常

### ISSUE THREAD

**Issue by Bearlele** [nonebot/nonebot2#1043]
**描述问题：**

一个handle()里使用多个bot.send_private_msg发送私信第一个bot.send_private_msg正常，但第二个bot.send_private_msg会抛出异常：
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 9}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

实际全部发送成功go-cqhttp端显示正常：
[INFO]: 发送好友 2587342146(2587342146)  的消息: [{"type":  ... (-2090719881) 

**如何复现？**

```
@private.handle()
async def _(bot: Bot, event: PrivateMessageEvent):
    await bot.send_private_msg(user_id=114514, message=Message('内容1'))
    反馈：
        [INFO] nonebot | Event will be handled by <Matcher from src.plugins.nonebot_plugin_Authenticate, type=message, priority=1, temp=False>

    await bot.send_private_msg(user_id=191810, message=Message('内容2'))
    反馈：
    nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 9}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
```

**期望的结果**

正常处理，不抛出异常

**环境信息：**

 - OS: [Linux Debian 5.16.0-0.bpo.4-amd64]
 - Python Version: [3.9.2]
 - Nonebot Version: [2.0.0b2]

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [cfa35b6]

**截图或日志**

```
06-15 16:11:06 [SUCCESS] nonebot | ONEBOT V11 2758026485 | [message.private.group]: Message 11580 from 3001640272 "2587342146"
06-15 16:11:06 [INFO] nonebot | Event will be handled by <Matcher from src.plugins.nonebot_plugin_Authenticate, type=message, priority=1, temp=False>
06-15 16:11:06 [INFO] nonebot | Matcher <Matcher from src.plugins.nonebot_plugin_Authenticate, type=message, priority=1, temp=False> running complete
06-15 16:11:06 [ERROR] nonebot | Running matcher <Matcher from src.plugins.nonebot_plugin_Authenticate, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/root/nonebot/src/plugins/nonebot_plugin_Authenticate/__init__.py", line 79, in _
    await bot.send_private_msg(user_id=user, message=Message('已给{0}({1})发送验证信息，请提醒对方及时进行验证\n您可以在3小时内发送新的QQ号以更改验证人'.format(info['card'],info['user_id'])))
  File "/usr/local/lib/python3.9/dist-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 23}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
```

**Comment by Bearlele** [comment]
gocq那边日志看起来是正常的：
```
[2022-06-15 16:16:08] [INFO]: 收到来自群 XXX(474079782) 内 XXX(3001640272) 的临时会话消息: 2587342146 
[2022-06-15 16:16:08] [INFO]: 发送好友 2587342146(2587342146)  的消息: [{"type":  ... (2037020112) 
```

**Comment by yanyongyu** [comment]
gocq的问题，与nb无关

**Comment by Bearlele** [comment]
了解了，我去gocq那边问问吧，感谢您的回答！

**Comment by synodriver** [comment]
确认是gocq的bug，这个是昵昵埋的[坑](https://github.com/Mrs4s/go-cqhttp/blob/master/coolq/bot.go#L373-L376)，昵昵应该知道（
