### ISSUE TITLE
call_api "get_group_member" get a error

### ISSUE THREAD

**Issue by huang12zheng** [nonebot/nonebot2#116]
**描述问题：**

* I am running code as follow,however, getting a error.
```py
@getMember.handle()
async def handle_gm(bot: Bot, event: Event, state: dict):
    group_id=event.group_id
    r1 = await bot.call_api("get_group_member",group_id=group_id)
```
* error info
```sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/local/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "bot.py", line 31, in <module>
    nonebot.run(app="bot:app")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 216, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 130, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 164, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/matcher.py", line 419, in run
    await handler(bot, event, self.state)
  File "src/plugins/remind.py", line 229, in handle_gm
    r1 = await bot.call_api("get_group_member",group_id=group_id)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 349, in call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 206, in fetch
    raise NetworkError("WebSocket API call timeout") from None
```

**期望的结果**

get_group_member

**环境信息：**

 - OS: [e.g. Linux]
 - Python Version: [e.g. 3.9.1]
 - Nonebot Version: [e.g. 2.0.0]
```sh
nb --version
nb: nonebot cli version 0.3.1
```
---------
* a more infomation:
config.hjson
```json
// 正向WS设置
    ws_config: {
        // 是否启用正向WS服务器
        enabled: true
        // 正向WS服务器监听地址
        host: 0.0.0.0
        // 正向WS服务器监听端口
        port: 6700
    }
    // 反向WS设置
    ws_reverse_servers: [
        // 可以添加多个反向WS推送
        {
            // 是否启用该推送
            enabled: true
            // 反向WS Universal 地址
            // 注意 设置了此项地址后下面两项将会被忽略
            // 留空请使用 ""
            reverse_url: ws://127.0.0.1:8080/cqhttp/ws
            // 反向WS API 地址
            reverse_api_url: ""
            // 反向WS Event 地址
            reverse_event_url: ""
            // 重连间隔 单位毫秒
            reverse_reconnect_interval: 3000
        }
    ]
```
----
> * question: Should reverse_api_url need to config?

**Comment by yanyongyu** [comment]
cqhttp并没有 `get_group_member` 这个接口，你可能是要 `get_group_member_list`
