### ISSUE TITLE
Bug: 事件响应器异常

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/nonebot2#130]
**描述问题：**

任意事件响应器
```
from nonebot import on_message
message = on_message()
```
对于任何消息都会引发异常
```
01-01 14:57:55 [DEBUG] nonebot | CQHTTP | Event Parser Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\PycharmProjects\nonebot2\venv\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\...\PycharmProjects\nonebot2\venv\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\...\PycharmProjects\nonebot2\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 307, in handle_message
    event = model.parse_obj(message)
  File "pydantic\main.py", line 520, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for GroupMessageEvent
anonymous
  none is not an allowed value (type=type_error.none.not_allowed)
```

**环境信息：**

 - OS: Windows 10 20H2 19042.685
 - Python Version: 3.8
 - Nonebot Version: 2.0.0a8 (从2.0.0a7升级)

**Comment by mnixry** [comment]
https://github.com/nonebot/nonebot2/blob/a966f8219285e6c8fe865c7a11eb40593a079b7f/nonebot/adapters/cqhttp/event.py#L88-L94
https://github.com/nonebot/nonebot2/blob/a966f8219285e6c8fe865c7a11eb40593a079b7f/nonebot/adapters/cqhttp/event.py#L182-L197

@yanyongyu  好像确实有问题 因为`anonymous`字段明显不是每个`event`都有的, 感觉加个`Optional`比较好

**Comment by yanyongyu** [comment]
这边确实是写错了，cqhttp里规定Anonymous是可选的，目前如果`GroupMessageEvent`解析失败会fallback到`MessageEvent`
