### ISSUE TITLE
Bug: 私聊发送文件在某些情况下会出现 RejectedException

### ISSUE THREAD

**Issue by Jerry-FaGe** [nonebot/nonebot2#1404]
**描述问题：**

私聊给 bot 发送文件在某些逻辑下会直接出现 RejectedException 异常，即使代码中并没有 matcher.reject() 。同样的逻辑在群聊文件中没有异常。

这个问题不太好描述，我已经整理了能稳定复现的代码

**如何复现？**

```Python
async def _upload_png_file(event: NoticeEvent) -> bool:
    return event.notice_type == "offline_file" and event.dict().get("file").get("name").endswith(".png")


# 检测图片文件上传事件
offline_png_info = on_notice(rule=Rule(_upload_png_file), priority=5)


@offline_png_info.handle()
async def _(event: NoticeEvent, state: T_State):
    await offline_png_info.send("输入“是”继续解析", at_sender=True)


@offline_png_info.got("yes")
async def _(event: Union[NoticeEvent, MessageEvent], state: T_State, yes: str = ArgPlainText()):
    if yes == "是":
        await png_file_info.finish("解析成功", at_sender=True)
```
ps: 我知道这么写不太符合规范，但貌似 got 的 prompt 参数貌似并不能支持 at_sender ，故使用了这种写法。

**期望的结果**

按照规定的流程：检测到图片上传 -> 询问用户是否解析 -> 返回解析结果

**环境信息：**

 - OS: Linux
 - Python Version: 3.8.10 venv
 - Nonebot Version: 2.0.0rc1

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: [v1.0.0-rc3](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3)

**截图或日志**

![image](https://user-images.githubusercontent.com/40235071/202699882-8c4c52d5-c864-4f80-b4f8-83c7c3caf0f0.png)

```log
11-18 19:55:49 [SUCCESS] nonebot | OneBot V11 XXX| [notice.offline_file]: {'time': 1668772549, 'self_id': XXX, 'post_type': 'notice', 'notice_type': 'offline_file',
'file': {'name': '00227-2252077014-masterpiece, best quality, extremely detailed, CG, unity 8k wallpaper,神子-83000,one-piece swimsuit, bottomless,.png', 'size': 535219, 'url': 'ht
tp://175.27.8.232/ftn_handler/cf22923cba38e31d3a15ef246286933f241a0e3b4c1abdc53c770ca19d576fa8970323947a605ebd9f1d215a1063dbb2f877615577e748be2e4cf3fd2ac16085'}, 'user_id': XXX}
11-18 19:55:49 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=src.plugins.ai_draw)
11-18 19:55:49 [INFO] nonebot | Matcher(type='notice', module=src.plugins.ai_draw) running complete
11-18 19:55:49 [ERROR] nonebot | Running Matcher(type='notice', module=src.plugins.ai_draw) failed.
Traceback (most recent call last):
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 104, in __call__
    values = await self.solve(**kwargs)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 216, in solve
    await param._solve(**params)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/params.py", line 144, in _solve
    return await task
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 415, in _key_getter
    await matcher.reject(prompt)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 507, in reject
    raise RejectedException
nonebot.exception.RejectedException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 721, in run
    permission = await self.update_permission(bot, event)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 656, in update_permission
    return USER(event.get_session_id(), perm=permission)
  File "/home/Jerry_FaGe/nonebot_b/nb_b_venv/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/event.py", line 57, in get_session_id
    raise ValueError("Event has no context!")
ValueError: Event has no context!
11-18 19:55:54 [SUCCESS] nonebot | OneBot V11 XXX| [message.private.friend]: Message -1698843090 from XXX"是"
```

**Comment by yanyongyu** [comment]
这个报错是由于你的事件没有提供session id导致的，nb无法判断这个事件是谁触发的，报错是as design的，建议通过custom model的方式给ob v11添加额外的gocq事件

**Comment by yanyongyu** [comment]
https://onebot.adapters.nonebot.dev/docs/api/v11/adapter#Adapter-add_custom_model

**Comment by Jerry-FaGe** [comment]
了解了，我再研究一下，谢谢。
