### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by beiyuouo** [nonebot/nonebot2#146]
**描述问题：**

builtin_plugins say函数无法发送富文本

**如何复现？**

使用builtin_plugins，/say [CQ:face,id=13]

**环境信息：**

 - OS: Ubuntu
 - Python 3.7
 - Nonebot Version: 2.0.0

**截图**

```
01-08 01:36:06 [ERROR] nonebot | Running matcher <Matcher from base, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.7/dist-packages/nonebot/__init__.py", line 217, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nonebot/drivers/fastapi.py", line 124, in run
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/lib/python3.7/dist-packages/nonebot/message.py", line 170, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.7/dist-packages/nonebot/matcher.py", line 496, in run
    await self.run_handler(handler, bot, event, state_)
  File "/usr/local/lib/python3.7/dist-packages/nonebot/matcher.py", line 482, in run_handler
    **{k: v for k, v in args.items() if params[k] is not None})
  File "awesome_bot/plugins/base.py", line 19, in say_unescape
    message = reduce(_unescape, event.get_message(), Message())  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/nonebot/adapters/__init__.py", line 229, in __init__
    self.extend(self._construct(message))
  File "/usr/local/lib/python3.7/dist-packages/nonebot/adapters/__init__.py", line 304, in extend
    for segment in obj:
  File "/usr/local/lib/python3.7/dist-packages/nonebot/adapters/cqhttp/message.py", line 238, in _construct
    for type_, data in _iter_message(msg):
  File "/usr/local/lib/python3.7/dist-packages/nonebot/adapters/cqhttp/message.py", line 232, in _iter_message
    r"),?\]", msg):
  File "/usr/lib/python3.7/re.py", line 230, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object

```

**Comment by lengthmin** [comment]
dev 分支中已修复，请等待发版
