### ISSUE TITLE
NotFoundError: No module named 'nonebot.log'wrong

### ISSUE THREAD

**Issue by nj005py** [nonebot/nonebot2#157]
**描述问题：**
windows环境，powershell
输入
nb plugin list
无法获取插件列表

ModuleNotFoundError: No module named 'nonebot.log'
Traceback (most recent call last):
File "d:\python\python38\lib\runpy.py", line 194, in run_module_as_main
return run_code(code, main_globals, None,
File "d:\python\python38\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "D:\Python\Python38\Scripts\nb.exe_main.py", line 4, in
File "d:\python\python38\lib\site-packages\nb_cli_init.py", line 6, in
from nb_cli.handlers import search_plugin, create_plugin, update_plugin, install_plugin
File "d:\python\python38\lib\site-packages\nb_cli\handlers.py", line 17, in
import nonebot.adapters
File "d:\python\python38\lib\site-packages\nonebot\adapters_init.py", line 18, in
from nonebot.utils import DataclassEncoder
File "d:\python\python38\lib\site-packages\nonebot\utils.py", line 8, in
from nonebot.log import logger
ModuleNotFoundError: No module named 'nonebot.log'

**环境信息：**

 - OS: windows10
 - Python Version: Python 3.8.7
 - Nonebot Version: [e.g. 2.0.0]

**Comment by yanyongyu** [comment]
请尝试卸载并重装 `nonebot` 或更新至最新版本

**Comment by nj005py** [comment]
在 Python38\Lib\site-packages下把nonebot的东西删掉，重装可以用了。应该是pip uninstall 1代的东西有残留
