### ISSUE TITLE
Bug:安装出现问题

### ISSUE THREAD

**Issue by PrayerT** [nonebot/nonebot2#1606]
**描述问题：**

python3.8.10，pip install nb-cli之后，使用nb指令或者nb create指令均出现报错

**如何复现？**

1.新装的ubuntu20.04 64位
2.pip install nb-cli
3.nb

**期望的结果**

正常使用

**环境信息：**

 - OS: ubuntu 20.04 64位
 - Python Version: 3.8.10
 - Nonebot Version: 1.0.1

**协议端信息：**

 - 协议端: 无
 - 协议端版本: 无

**截图或日志**

root@prayer:~# nb
/bin/sh: 1: python: not found
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/__main__.py", line 7, in main
    anyio.run(cli_main)
  File "/usr/local/lib/python3.8/dist-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/__init__.py", line 29, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/__init__.py", line 84, in cli
    for sub_cmd_name in await run_sync(command.list_commands)(ctx):
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/customize.py", line 155, in list_commands
    scripts: List[click.Command] = self._load_scripts(ctx)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/cashews/wrapper.py", line 289, in _call
    return await decorator(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cashews/decorators/cache/simple.py", line 43, in _wrap
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/cli/customize.py", line 130, in _load_scripts
    scripts = await list_scripts()
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/meta.py", line 105, in wrapper
    version = await get_python_version(
  File "/usr/local/lib/python3.8/dist-packages/cashews/wrapper.py", line 289, in _call
    return await decorator(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cashews/decorators/cache/simple.py", line 43, in _wrap
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/meta.py", line 85, in get_python_version
    python_path = await get_default_python()
  File "/usr/local/lib/python3.8/dist-packages/cashews/wrapper.py", line 289, in _call
    return await decorator(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cashews/decorators/cache/simple.py", line 43, in _wrap
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/meta.py", line 72, in get_default_python
    return json.loads(stdout.strip())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yanyongyu** [comment]
`nb -py python3`
