### ISSUE TITLE
Question: Can't run with Dingdingbot adapter

### ISSUE THREAD

**Issue by wei-z-git** [nonebot/nonebot2#1702]
**描述问题：**

nb create时adapter选择钉钉机器人，创建项目后nb run报错：
```
nb run --reload
Started reloader with process [55953].
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nonebot/adapters/ding/__init__.py", line 11, in <module>
    from .bot import Bot as Bot
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nonebot/adapters/ding/bot.py", line 15, in <module>
    from nonebot.drivers import Driver, HTTPConnection, HTTPRequest, HTTPResponse
ImportError: cannot import name 'HTTPConnection' from 'nonebot.drivers' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nonebot/drivers/__init__.py)
```

**如何复现？**

1. nb create
2. 选择adapter时选择钉钉机器人
3. 创建完毕后nb run

**期望的结果**

正常运行

**环境信息：**

 - OS: macOS 13.2
 - Python Version: 3.10.5
 - Nonebot Version: 如何查看nonebot version？
 - nb-cli: nonebot cli version 1.0.4

**协议端信息：**

 - 协议端: 不涉及
 - 协议端版本: 不涉及

**截图或日志**

报错详见上

**Comment by yanyongyu** [comment]
钉钉适配器目前不可用，无人维护

**Comment by wei-z-git** [comment]
soga, 原来如此，提议后续可以移除此适配器或进行注释
