### ISSUE TITLE
Plugin: 与ChatGpt聊天

### ISSUE THREAD

**Issue by nikissXI** [nonebot/nonebot2#1916]
**插件名称：**

与ChatGpt聊天

**插件功能：**

基于accessToken登录的chatgpt聊天插件

**PyPI 项目名：**

nonebot-plugin-talk-with-chatgpt

**插件 import 包名：**

nonebot_plugin_talk_with_chatgpt

**插件项目仓库/主页链接：**

https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_talk_with_chatgpt

**标签：**

[{"label":"chatgpt","color":"#1a834e"}]

**Comment by nikissXI** [comment]
111

**Comment by nikissXI** [comment]
> # 📃 商店发布检查结果
> > Plugin: 与ChatGpt聊天
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 插件加载测试未通过。测试输出插件 nonebot_plugin_talk_with_chatgpt 的信息如下：
>       name         : nonebot-plugin-talk-with-chatgpt     
>        version      : 0.1.0                                
>        description  : Nonebot2 基于accessToken登录的chatgpt聊天插件 
>       
>       dependencies
>        - httpx >=0.22.0
>        - nonebot-adapter-onebot >=2.0.0
>        - nonebot2 >=2.0.0rc1
>   插件 nonebot_plugin_talk_with_chatgpt 依赖的插件如下：
>       
>   插件 nonebot_plugin_talk_with_chatgpt 加载出错：
>       04-11 09:19:36 [SUCCESS] nonebot | NoneBot is initializing...
>       04-11 09:19:36 [INFO] nonebot | Current Env: prod
>       04-11 09:19:37 [ERROR] nonebot | Failed to import "nonebot_plugin_talk_with_chatgpt"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/runner.py", line 4, in <module>
>           valid = load_plugin("nonebot_plugin_talk_with_chatgpt")
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_talk_with_chatgpt/__init__.py", line 11, in <module>
>           from .data_handle import req_chatgpt
>         File "/home/runner/.cache/pypoetry/virtualenvs/plugin-test-rYmcgvOP-py3.10/lib/python3.10/site-packages/nonebot_plugin_talk_with_chatgpt/data_handle.py", line 3, in <module>
>           from ujson import loads
>       ModuleNotFoundError: No module named 'ujson'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)

again
