### ISSUE TITLE
Question: 运行预处理函数中调用 matcher.finish 出错

### ISSUE THREAD

**Issue by StarHeartHunt** [nonebot/nonebot2#192]
**描述问题：**

在 `运行预处理` 函数中调用 `matcher.finish()`出错，无法找到 `bot` 对象

**如何复现？**

1. 定义一个函数，如
```python
async def check_limit(matcher: Matcher, bot: Bot, event: Event, state: T_State):
```
2. 用 `@run_preprocessor` 装饰
3. 在其中调用 `matcher.finish()`

**期望的结果**

`matcher` 被 `finish`

**环境信息：**

 - OS: Linux
 - Python Version: 3.8
 - Nonebot Version: 2.0.0a8.post2

**日志**
```python
02-04 17:08:22 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/python3/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/python3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 155, in _run_matcher
    await asyncio.gather(*coros)
  File "src/plugins/RateLimit/data_source.py", line 41, in check_limit
    await matcher.finish()
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/matcher.py", line 407, in finish
    bot = current_bot.get()
LookupError: <ContextVar name='current_bot' at 0x7fa567652450>
```

**Comment by yanyongyu** [comment]
预处理阶段matcher尚未生成，你应该直接调用bot.send来发送
