### ISSUE TITLE
装nb-cli运行的时候出现的错误，试了很多方法都解决不了（有解释器，一开始以为是和其他包冲突了，但是重新搭建环境还是不行）

### ISSUE THREAD

**Issue by Gl985** [nonebot/nonebot2#1976]
```
Future exception was never retrieved
future: <Future finished exception=PythonInterpreterError('无法找到可用的 Python 解
释器. stdout=b\'Active code page: 65001\\r\\n"D:\\\\\\\\smotce\\\\\\\\Anocanda\\\\\\\\envs\\\\\\\\py38\\\\\\\\python.exe"\\r\\n\'')>
Traceback (most recent call last):
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 79, in _get_env_python
    raise PythonInterpreterError(
nb_cli.exceptions.PythonInterpreterError: 无法找到可用的 Python 解释器. stdout=b'Active code page: 65001\r\n"D:\\\\smotce\\\\Anocanda\\\\envs\\\\py38\\\\python.exe"\r\n'
Future exception was never retrieved
future: <Future finished exception=PythonInterpreterError('无法找到可用的 Python 解
释器. stdout=b\'Active code page: 65001\\r\\n"D:\\\\\\\\smotce\\\\\\\\Anocanda\\\\\\\\envs\\\\\\\\py38\\\\\\\\python.exe"\\r\\n\'')>
Traceback (most recent call last):
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 102, in get_python_version
    python_path = await get_default_python()
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 89, in get_default_python
    return await _get_env_python()
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\wrapper\decorators.py", line 56, in _call
    return await thunder_protection(decorator)(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\locked.py", line 101, in _wrapper
    return await task
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 79, in _get_env_python
    raise PythonInterpreterError(
nb_cli.exceptions.PythonInterpreterError: 无法找到可用的 Python 解释器. stdout=b'Active code page: 65001\r\n"D:\\\\smotce\\\\Anocanda\\\\envs\\\\py38\\\\python.exe"\r\n'
Traceback (most recent call last):
  File "D:\smotce\Anocanda\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\smotce\Anocanda\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\smotce\Anocanda\envs\py38\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\__main__.py", line 10, in main
    anyio.run(cli_main, *args)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\_core\_eventloop.py", 
line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "D:\smotce\Anocanda\envs\py38\lib\asyncio\runners.py", line 44, in run      
    return loop.run_until_complete(main)
  File "D:\smotce\Anocanda\envs\py38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\cli\utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\cli\utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\from_thread.py", line 
49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "D:\smotce\Anocanda\envs\py38\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "D:\smotce\Anocanda\envs\py38\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\cli\commands\project.py", line 343, in run
    proc = await run_project(exist_bot=Path(file))
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 122, in wrapper
    version = await get_python_version(
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\wrapper\decorators.py", line 56, in _call
    return await thunder_protection(decorator)(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\locked.py", line 101, in _wrapper
    return await task
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 102, in get_python_version
    python_path = await get_default_python()
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 89, in get_default_python
    return await _get_env_python()
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\wrapper\decorators.py", line 56, in _call
    return await thunder_protection(decorator)(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\locked.py", line 101, in _wrapper
    return await task
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "D:\smotce\Anocanda\envs\py38\lib\site-packages\nb_cli\handlers\meta.py", line 79, in _get_env_python
    raise PythonInterpreterError(
nb_cli.exceptions.PythonInterpreterError: 无法找到可用的 Python 解释器. stdout=b'Active code page: 65001\r\n"D:\\\\smotce\\\\Anocanda\\\\envs\\\\py38\\\\python.exe"\r\n'
```

**Comment by StarHeartHunt** [comment]
`Active code page: 65001\r\n"`
关掉 utf-8 实验性支持

**Comment by Gl985** [comment]
> `Active code page: 65001\r\n"` 关掉 utf-8 实验性支持

谢谢老哥，刚刚解决了，你的话提醒了我，我的cmd显示了Active code page: 65001，我在注册表中将其隐藏然后成功运行了
