### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by NealScx** [nonebot/nonebot2#2185]
### 操作系统

Linux

### Python 版本

3.9.15

### NoneBot 版本

2.0.0b5

### 适配器

onebot==2.1.3

### 协议端

go-cqhttp 1.1.0

### 描述问题

root@2024:~/neal-bot# nb plugin update nonebot-plugin-bilichat
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/plugin.py", line 55, in update
    update_plugin(name, index)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/plugin.py", line 125, in update_plugin
    plugin = _get_plugin(package, "Plugin name you want to update?")
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/plugin.py", line 90, in _get_plugin
    return _get_module(Plugin, package, question)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/utils.py", line 118, in _get_module
    modules = _get_modules(module_type)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/utils.py", line 99, in _get_modules
    items = resp.json()
  File "/usr/local/lib/python3.9/dist-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 复现步骤

安装或者更新任何插件都会出现该问题  麻烦大佬帮忙看下是什么问题

**Comment by mute23-code** [comment]
nb_cli的问题怎么发到这来了🤔
