### ISSUE TITLE
Bug: RuntimeError: Cannot call "send" once a close message has been sent.

### ISSUE THREAD

**Issue by danuonuo** [nonebot/nonebot2#225]
**问题描述：**
使用nb-cli运行最小实例时出现RuntimeError: Cannot call "send" once a close message has been sent.
**复现：**

使用nb-cli按照官方文档创建最小实例。
**期望的结果**
Traceback (most recent call last):
File "bot.py", line 10, in
nonebot.run()
File "/usr/local/lib/python3.8/dist-packages/nonebot/init.py", line 217, in run
get_driver().run(host, port, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 118, in run
uvicorn.run(app or self.server_app,
File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 362, in run
server.run()
File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 390, in run
loop.run_until_complete(self.serve(sockets=sockets))

File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 154, in run_asgi
result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in call
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 199, in call
await super().call(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 111, in call
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 146, in call
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 58, in call
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in call
await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 283, in handle
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 57, in app
await func(session)
File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 247, in app
await dependant.call(**values)
File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 190, in _handle_ws_reverse
await ws.accept()
File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 222, in accept
await self.websocket.accept()
File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 76, in accept
await self.send({"type": "websocket.accept", "subprotocol": subprotocol})
File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 70, in send
raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.

**环境信息：**

OS: [Ubuntu20.04 LTS]
Python Version: [3.8.5]
Nonebot Version: [0.3.2]

**截图**

![image](https://user-images.githubusercontent.com/40296672/108618223-2ebc4800-7457-11eb-9d9e-9f05937e650f.png)

PS: Sorry，我知道我提的issue有点点多，我也是按照文档部署的，但我也不知道我为啥会遇到这么多问题2333，总之还是谢谢开发者们啦

**Comment by yanyongyu** [comment]
请确认一下nonebot2的版本是否为最新版

**Comment by danuonuo** [comment]
> 请确认一下nonebot2的版本是否为最新版，某个老版本有此问题
> 
> 
> 
> ```
> 
> pip show nonebot2
> 
> ```
> 
> 
> 
> 此情况可能为老版本的token检查错误，如果新版本中依然有此问题，请确认ws连接是否正常

请问一个go-cqhttp实例一次只能运行**一个**nonebot2的bot.py式插件吗？
我发现我提该issue问题仅仅会在运行多于一个nonebot2 bot.py时出现，并且错误信息为ws返回403，提示已经有一个连接。
