### ISSUE TITLE
Plugin: nonebot_plugin_muteme

### ISSUE THREAD

**Issue by XTxiaoting14332** [nonebot/nonebot2#2250]
### PyPI 项目名

nonebot-plugin-muteme

### 插件 import 包名

nonebot_plugin_muteme

### 标签

[{"label":"禁言","color":"#e45b8d"},{"label":"muteme","color":"#5bc2e4"}]

**Comment by XTxiaoting14332** [comment]
github地址:https://github.com/XTxiaoting14332/nonebot-plugin-muteme

**Comment by XTxiaoting14332** [comment]
> #  商店发布检查结果
> > Plugin: nonebot-plugin-muteme
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-muteme 的信息如下：
>        name         : nonebot-plugin-muteme                  
>        version      : 0.0.1                                  
>        description  : 适用于nonebot2 v11的禁言自己插件 高仿 @能干辉 的muteme 
>       
>       dependencies
>        - nonebot2 *
>   插件 nonebot-plugin-muteme 依赖的插件如下：
>       
>   插件 nonebot_plugin_muteme 加载出错：
>       08-07 13:07:30 [SUCCESS] nonebot | NoneBot is initializing...
>       08-07 13:07:30 [INFO] nonebot | Current Env: prod
>       08-07 13:07:30 [ERROR] nonebot | Failed to import "nonebot_plugin_muteme"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-muteme-nonebot_plugin_muteme-test/runner.py", line 15, in <module>
>           plugin = load_plugin("nonebot_plugin_muteme")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-muteme-nonebot_plugin_muteme-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-muteme-nonebot_plugin_muteme-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
>           module = importlib.import_module(name)
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-muteme-nonebot_plugin_muteme-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-muteme-nonebot_plugin_muteme-test/.venv/lib/python3.10/site-packages/nonebot_plugin_muteme/__init__.py", line 1, in <module>
>           from nonebot.adapters.onebot.v11 import Message, MessageSegment
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> bulb 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> muscle Powered by [NoneFlow](https://hub.xb6868.com/nonebot/noneflow)

已修复

**Comment by XTxiaoting14332** [comment]
> # 📃 商店发布检查结果
> 
> > Plugin: nonebot_plugin_muteme
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> <pre><code><li>⚠️ 项目 <a href="https://github.com/XTxiaoting14332/nonebot_plugin_muteme">主页</a> 返回状态码 301。<dt>请确保您的项目主页可访问。</dt></li></code></pre>
> <details><summary>详情</summary><pre><code><li>✅ 标签: 禁言-#e45b8d, muteme-#5bc2e4。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-muteme/">nonebot-plugin-muteme</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/5785995769">加载测试</a> 通过。</li><li>✅ 插件类型: application。</li><li>✅ 插件支持的适配器: 所有。</li></code></pre></details>
> 
> ---
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
> 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> 
> 

已修复

**Comment by XTxiaoting14332** [comment]
> # 📃 商店发布检查结果
> 
> > Plugin: nonebot_plugin_muteme
> 
> **⚠️ 在发布检查过程中，我们发现以下问题：**
> <pre><code><li>⚠️ 项目 <a href="https://github.com/XTxiaoting14332/nonebot_plugin_muteme">主页</a> 返回状态码 301。<dt>请确保您的项目主页可访问。</dt></li></code></pre>
> <details><summary>详情</summary><pre><code><li>✅ 标签: 禁言-#e45b8d, muteme-#5bc2e4。</li><li>✅ 包 <a href="https://pypi.org/project/nonebot-plugin-muteme/">nonebot-plugin-muteme</a> 已发布至 PyPI。</li><li>✅ 插件 <a href="https://github.com/nonebot/nonebot2/actions/runs/5786118378">加载测试</a> 通过。</li><li>✅ 插件类型: application。</li><li>✅ 插件支持的适配器: 所有。</li></code></pre></details>
> 
> ---
> 
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
> 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> 
> 

已修复 忘记改项目地址了……

**Comment by XTxiaoting14332** [comment]
已修复所有问题

**Comment by XTxiaoting14332** [comment]
已更新
