### ISSUE TITLE
Bug: 添加aliases后MatcherGroup没有_default_parser

### ISSUE THREAD

**Issue by SDchao** [nonebot/nonebot2#25]
例如如下命令：
```
five_query = on_command("5e", aliases={"5E"}, priority=50)

@five_query.handle()
async def five_query_first(bot: Bot, event: Event, status: dict):
    arg = str(event.message).strip()
    if arg:
        status["username"] = arg


@five_query.got("username", prompt="请输入查询用户名")
async def five_query_got_username(bot: Bot, event: Event, status: dict):
```

若用户发送 !5e，prompt发出后回复用户名，则会出现以下异常：
```
10-11 11:45:08 [ERROR] nonebot | Running matcher <Matcher from five_e_search, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/nonebot-sdchao-v2-aazKdxEz-py3.7/lib/python3.7/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/home/pi/.cache/pypoetry/virtualenvs/nonebot-sdchao-v2-aazKdxEz-py3.7/lib/python3.7/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/home/pi/.cache/pypoetry/virtualenvs/nonebot-sdchao-v2-aazKdxEz-py3.7/lib/python3.7/site-packages/nonebot/message.py", line 44, in _run_matcher
    await matcher.run(bot, event, state)
  File "/home/pi/.cache/pypoetry/virtualenvs/nonebot-sdchao-v2-aazKdxEz-py3.7/lib/python3.7/site-packages/nonebot/matcher.py", line 248, in run
    await handler(bot, event, self.state)
  File "/home/pi/.cache/pypoetry/virtualenvs/nonebot-sdchao-v2-aazKdxEz-py3.7/lib/python3.7/site-packages/nonebot/matcher.py", line 410, in wrapper
    await parser(bot, event, state)
  File "/home/pi/.cache/pypoetry/virtualenvs/nonebot-sdchao-v2-aazKdxEz-py3.7/lib/python3.7/site-packages/nonebot/matcher.py", line 395, in _key_parser
    parser = args_parser or self._default_parser
AttributeError: 'MatcherGroup' object has no attribute '_default_parser'
```

将on_command中aliases参数去除后，工作正常。
```
five_query = on_command("5e", priority=50)
```

**Comment by yanyongyu** [comment]
已经于 https://github.com/nonebot/nonebot2/commit/d71260ed685732c8b9865e32dc39858094763ac5 修复
