### ISSUE TITLE
Bug: cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [nonebot/nonebot2#2574]
### 操作系统

Windows

### Python 版本

3.12.2

### NoneBot 版本

2.2.0

### 适配器

OneBot V11

### 协议端

无

### 描述问题

创建机器人后启动报 cannot import name 'ModelField' from 'pydantic.fields'

### 复现步骤

1.使用nb create创建机器人
2.使用nb run --reload启动报错
使用mac端以及win端均出现该问题

### 截图或日志

```toml
[project]
name = "nonebot-plugin-osu-tournament"
version = "0.1.0"
description = "nonebot-plugin-osu-tournament"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "Console", module_name = "nonebot.adapters.console" }
]
plugins = []
plugin_dirs = ["src/plugins"]
builtin_plugins = ["echo", "single_session"]
```
```
F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament>nb run --reload
使用 Python: F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament\.venv\Scripts\python.exe
启动重载监视，当前进程 [20392].
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament\.venv\Lib\site-packages\nonebot\adapters\onebot\__init__.py", line 12, in <module>
    from .v11 import Bot as V11Bot
  File "F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\__init__.py", line 15, in <module>
    from .adapter import Adapter as Adapter
  File "F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 31, in <module>
    from nonebot.adapters.onebot.collator import Collator
  File "F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament\.venv\Lib\site-packages\nonebot\adapters\onebot\collator.py", line 10, in <module>
    from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields' (F:\YC\Code\Nonebot_Project\nonebot-plugin-osu-tournament\.venv\Lib\site-packages\pydantic\fields.py)
```
停止重载监视

**Comment by lgc2333** [comment]
尝试手动降级pydantic至v1：`pip install "pydantic<2"`

**Comment by Tsurumaki-Kokoro** [comment]
已解决

**Comment by yangjiaji1795** [comment]
怎么解决的？

**Comment by yanyongyu** [comment]
> 怎么解决的？

降级 pydantic 至 v1，上面已给出降级方法

**Comment by yangjiaji1795** [comment]
ok了，是我复制代码复制错了。

**Comment by w-w-www** [comment]
遇到同样的问题，复制之前的解决方案尝试几遍都没有解决
.\.venv\Scripts\activate.bat
pip install --force-reinstall 'pydantic~=1.10'
后面发现，其实是**虚拟环境没有成功激活**
在我的电脑（window11），应该为
.\.venv\Scripts\activate
pip install --force-reinstall 'pydantic~=1.10'
现在不再报之前的错误。
