### ISSUE TITLE
mah adapter 不能接受好友请求

### ISSUE THREAD

**Issue by notnotype** [nonebot/nonebot2#271]
**描述问题：**

mah adapter 不能接受好友请求

**如何复现？**

1，使用mah adapter
2， 接受

**环境信息：**

 - OS: [e.g. win10]
 - Python Version: 3.8
 - Nonebot Version: 2.0.11

**log**

```
03-07 21:54:35 [ERROR] nonebot | Running matcher <Matcher from welcome, type=request, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\adapters\mirai\utils.py", line 91, in wrapper
    data = await function(*args, **kwargs)
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\adapters\mirai\bot.py", line 55, in post
    response.raise_for_status()
  File "D:\Program FIles\Python38\lib\site-packages\httpx\_models.py", line 1105, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: http://127.0.0.1:8080/resp/newFriendRequestEvent
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program FIles\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\pydevd.py", line 2167, in <module>
    main()
  File "D:\Program FIles\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\pydevd.py", line 2158, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program FIles\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\pydevd.py", line 1470, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "D:\Program FIles\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program FIles\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Notype/workplace/timetable-bot/bot.py", line 34, in <module>
    nonebot.run()
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
  File "D:\Program FIles\Python38\lib\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "D:\Program FIles\Python38\lib\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "D:\Program FIles\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "D:\Program FIles\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "D:\Program FIles\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "D:\Program FIles\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "D:\Program FIles\Python38\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\matcher.py", line 586, in run
    await self.run_handler(handler, bot, event, state_)
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\matcher.py", line 571, in run_handler
    await handler(
  File "src/plugins\welcome.py", line 25, in _
    await event.approve(bot)
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\adapters\mirai\event\request.py", line 34, in approve
    return await bot.api.post('/resp/newFriendRequestEvent',
  File "D:\Program FIles\Python38\lib\site-packages\nonebot\adapters\mirai\utils.py", line 93, in wrapper
    raise exception.NetworkError('mirai')
nonebot.exception.NetworkError: mirai
```

**Comment by yanyongyu** [comment]
@mnixry
