### ISSUE TITLE
Bug: nonebot无法正常初始化

### ISSUE THREAD

**Issue by ZacharyChenpk** [nonebot/nonebot2#284]
**环境信息：**

 - OS: CentOS
 - Python Version: 3.8
 - Nonebot Version: 2.0.0a10

bot.py代码
```
import nonebot
from nonebot.adapters.mirai import WebsocketBot
from nonebot.adapters.cqhttp import Bot as CQHTTPBot
from os import path

nonebot.init()
driver = nonebot.get_driver()
driver.register_adapter("cqhttp", CQHTTPBot)
nonebot.load_builtin_plugins()
nonebot.load_plugin("pot.plugins.pot")

app = nonebot.get_asgi()

if __name__ == "__main__":
    nonebot.run()
```

报错信息：
```
# python3.8 bot.py 
03-12 16:02:38 [INFO] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    nonebot.init()
  File "/usr/local/python3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 175, in init
    env = Env()
  File "/usr/local/python3.8/lib/python3.8/site-packages/nonebot/config.py", line 38, in __init__
    __pydantic_self__).__init__(**__pydantic_self__._build_values(
  File "/usr/local/python3.8/lib/python3.8/site-packages/nonebot/config.py", line 53, in _build_values
    return deep_update(self._build_secrets_files(_secrets_dir),
TypeError: 'NoneType' object is not callable
```

**Comment by yanyongyu** [comment]
升级`nonebot=2.0.0a11`版本或者降级`pydantic=1.7.3`

**Comment by ZacharyChenpk** [comment]
升级后nonebot.adapters.cqhttp和nonebot.adapters.mirai均无法import，请问是adapters的API接口有变动吗

**Comment by yanyongyu** [comment]
安装`nonebot-adapter-cqhttp`和`nonebot-adapter-mirai`
