### ISSUE TITLE
Plugin: nonebot-plugin-fun-content

### ISSUE THREAD

**Issue by chsiyu** [nonebot/nonebot2#2977]
### PyPI 项目名

nonebot-plugin-fun-content

### 插件 import 包名

nonebot_plugin_fun_content

### 标签

[]

### 插件配置项

```dotenv
无需配置，直接使用
```

**Comment by chsiyu** [comment]
> # 📃 商店发布检查结果
> > 插件： nonebot-plugin-fun-content
> 
> **⚠️在发布检查过程中，我们发现以下问题：**
> 
> ```
> * ⚠️ 无法获取到插件元数据。请确保插件正常加载。* ⚠️ 插件加载测试未通过。测试输出插件 nonebot-plugin-fun-content 的信息如下：
>        name         : nonebot-plugin-fun-content     
>        version      : 0.1.6                          
>        description  : 从多个 API 获取趣味内容，如一言、土味情话、舔狗日记等。 
>       
>       dependencies
>        - httpx >=0.23.0,<0.24.0
>        - nonebot2 >=2.3,<3.0
>   插件 nonebot-plugin-fun-content 依赖的插件如下：
>       
>   插件 nonebot_plugin_fun_content 加载出错：
>       09-24 13:59:36 [SUCCESS] nonebot | NoneBot is initializing...
>       09-24 13:59:36 [INFO] nonebot | Current Env: prod
>       09-24 13:59:36 [ERROR] nonebot | Failed to import "nonebot_plugin_fun_content"
>       Traceback (most recent call last):
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-fun-content-nonebot_plugin_fun_content-test/runner.py", line 16, in <module>
>           plugin = load_plugin("nonebot_plugin_fun_content")
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-fun-content-nonebot_plugin_fun_content-test/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
>           return manager.load_plugin(module_path)
>       > File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-fun-content-nonebot_plugin_fun_content-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
>           module = importlib.import_module(self._third_party_plugin_ids[name])
>         File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-fun-content-nonebot_plugin_fun_content-test/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
>           super().exec_module(module)
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-fun-content-nonebot_plugin_fun_content-test/.venv/lib/python3.12/site-packages/nonebot_plugin_fun_content/__init__.py", line 4, in <module>
>           from nonebot.adapters.onebot.v11 import MessageSegment, Message
>       ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 详情
> 💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。 💡 当插件加载测试失败时，请发布新版本后在当前页面下评论任意内容以触发测试。
> 
> ♻️ 评论已更新至最新检查结果
> 
> 💪 由 [NoneFlow](https://github.com/nonebot/noneflow) 提供支持

已更新

**Comment by chsiyu** [comment]
已更新
