### ISSUE TITLE
Docs: 更新文档

### ISSUE THREAD

**Issue by yanyongyu** [nonebot/nonebot2#3]
- [ ] 完成各模块 sphinx 文档注释
	- [x] \_\_init\_\_.py
	- [x] typing.py
	- [x] log.py
	- [x] exception.py
	- [x] config.py
	- [ ] plugin.py
	- [ ] message.py
	- [ ] matcher.py
	- [ ] permission.py
	- [ ] rule.py
	- [ ] utils.py
	- [ ] drivers
	- [ ] adapters
- [ ] 完成指南

**Comment by lengthmin** [comment]
https://github.com/nonebot/nonebot2/blob/04a3712bc71ea8faa121808c6509d50b1d05548e/archive/2.0.0a6/guide/loading-a-plugin.md#L14

https://github.com/nonebot/nonebot2/blob/2bf63ce8aa1d5426c2103a22cca2dd701c7f6233/docs/guide/loading-a-plugin.md#L14

fix: #96

**Comment by nj005py** [comment]
windows环境，powershell
**输入**
nb plugin list
**ModuleNotFoundError: No module named 'nonebot.log'**
Traceback (most recent call last):
  File "d:\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python38\Scripts\nb.exe\__main__.py", line 4, in <module>
  File "d:\python\python38\lib\site-packages\nb_cli\__init__.py", line 6, in <module>
    from nb_cli.handlers import search_plugin, create_plugin, update_plugin, install_plugin
  File "d:\python\python38\lib\site-packages\nb_cli\handlers.py", line 17, in <module>
    import nonebot.adapters
  File "d:\python\python38\lib\site-packages\nonebot\adapters\__init__.py", line 18, in <module>
    from nonebot.utils import DataclassEncoder
  File "d:\python\python38\lib\site-packages\nonebot\utils.py", line 8, in <module>
    from nonebot.log import logger
ModuleNotFoundError: No module named 'nonebot.log'

**Comment by shoucandanghehe** [comment]
https://github.com/nonebot/nonebot2/blob/80bf73e0e95afbb3e29b1a3efbbc0060d2ad454e/website/versioned_docs/version-2.0.0-beta.1/tutorial/plugin/introduction.md?plain=1#L46
`foo.py`是否应为`foo`

**Comment by yanyongyu** [comment]
> https://github.com/nonebot/nonebot2/blob/80bf73e0e95afbb3e29b1a3efbbc0060d2ad454e/website/versioned_docs/version-2.0.0-beta.1/tutorial/plugin/introduction.md?plain=1#L46
> 
> 
> `foo.py`是否应为`foo`

已在dev更新
