### ISSUE TITLE
Plugin: 语音点歌

### ISSUE THREAD

**Issue by Onimaimai** [nonebot/nonebot2#3036]
### PyPI 项目名

nonebot-plugin-voicemusic

### 插件 import 包名

nonebot_plugin_voicemusic

### 标签

[]

### 插件配置项

_No Response_

**Comment by Onimaimai** [comment]
update

**Comment by Onimaimai** [comment]
不知道为什么🥺：

10-19 13:57:14 [SUCCESS] nonebot | NoneBot is initializing...
10-19 13:57:14 [INFO] nonebot | Current Env: prod
10-19 13:57:15 [SUCCESS] nonebot | Succeeded to load plugin "publish" from "src.plugins.publish"
10-19 13:57:15 [SUCCESS] nonebot | Running NoneBot...
10-19 13:57:15 [INFO] nonebot | Application startup completed.
10-19 13:57:15 [SUCCESS] nonebot | GitHub *** | [issue_comment.created]: IssueCommentCreated 1141510[48](https://github.com/nonebot/nonebot2/actions/runs/11415104855/job/31764782436#step:6:49)55 from sender Onimaimai in repository nonebot/nonebot2
10-19 13:57:16 [INFO] nonebot | Event will be handled by Matcher(type='', module=src.plugins.publish, lineno=1[49](https://github.com/nonebot/nonebot2/actions/runs/11415104855/job/31764782436#step:6:50))
10-19 13:57:16 [INFO] publish | 运行命令: ['git', 'config', '--global', 'safe.directory', '*']
10-19 13:57:16 [INFO] publish | 运行命令: ['pre-commit', 'install', '--install-hooks']
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'switch', '-C', 'publish/issue3036']
10-19 13:57:18 [INFO] publish | 正在更新文件: assets/plugins.json
10-19 13:57:18 [INFO] publish | 文件更新完成
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'config', '--global', 'user.name', 'Onimaimai']
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'config', '--global', 'user.email', 'Onimaimai@users.noreply.github.com']
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'add', '-A']
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'commit', '-m', ':beers: publish plugin 语音点歌 (#3036)']
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'add', '-A']
10-19 13:57:18 [INFO] publish | 运行命令: ['git', 'commit', '-m', ':beers: publish plugin 语音点歌 (#3036)']
10-19 13:57:19 [INFO] nonebot | Matcher(type='', module=src.plugins.publish, lineno=149) running complete
10-19 13:57:19 [ERROR] nonebot | Running Matcher(type='', module=src.plugins.publish, lineno=149) failed.
Traceback (most recent call last):
  File "/app/src/plugins/publish/utils.py", line 132, in commit_and_push
    run_shell_command(["git", "commit", "-m", commit_message])
  File "/app/src/plugins/publish/utils.py", line 65, in run_shell_command
    r = subprocess.run(command, check=True, capture_output=True)
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'commit', '-m', ':beers: publish plugin 语音点歌 (#3036)']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bot.py", line 98, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.11/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/usr/local/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 8[50](https://github.com/nonebot/nonebot2/actions/runs/11415104855/job/31764782436#step:6:51), in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/usr/local/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/app/src/plugins/publish/__init__.py", line 202, in handle_publish_check
    commit_and_push(result, branch_name, issue_number)
  File "/app/src/plugins/publish/utils.py", line 136, in commit_and_push
    run_shell_command(["git", "commit", "-m", commit_message])
  File "/app/src/plugins/publish/utils.py", line 65, in run_shell_command
    r = subprocess.run(command, check=True, capture_output=True)
  File "/usr/local/lib/python3.11/subprocess.py", line [57](https://github.com/nonebot/nonebot2/actions/runs/11415104855/job/31764782436#step:6:58)1, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'commit', '-m', ':beers: publish plugin 语音点歌 (#3036)']' returned non-zero exit status 1.
10-19 13:57:19 [INFO] nonebot | Shutting down
10-19 13:57:19 [INFO] nonebot | Waiting for application shutdown.
10-19 13:57:19 [INFO] nonebot | Application shutdown complete.

**Comment by Onimaimai** [comment]
1

**Comment by Onimaimai** [comment]
哦哦是配置项的问题

**Comment by kanbereina** [comment]
①你没有设置`插件配置项`，导致`driver.config`不存在此属性。

②你使用了一些不必要的方法来响应用户消息。
通过分析源码，可知你使用了`on_message`响应器，而此响应器会对所有消息进行处理，并输出日志。
同时，发现你在`on_message`响应后使用正则来匹配固定命令后的参数。
综合来看，如果你想使用原生nb实现命令处理，使用`on_command`响应器会比`on_message`响应器更高效。
至于获取命令参数，则可使用`nonebot.params`中的`CommandArg`等方法直接获取命令后参数，详细请查阅nonebot文档。

**Comment by Onimaimai** [comment]
谢谢，补充config.py，修改指令逻辑

**Comment by Onimaimai** [comment]
本地pip安装插件可用，商店检测结果发不出

**Comment by zhongwen-4** [comment]
其实是测试流程坏掉了(

**Comment by tkgs0** [comment]
为什么要手动转码音频文件, 直接将下载的音频数据传给 `MessageSegment.record()` 不行吗?

**Comment by tkgs0** [comment]
update

**Comment by yanyongyu** [comment]
插件元数据缺少配置项

**Comment by Onimaimai** [comment]
update

**Comment by tkgs0** [comment]
兄弟你在干嘛啊兄弟,
你加了config=Config, 就不要merge我PR的了啊
![S41020-18300917_com kiwibrowser browser](https://github.com/user-attachments/assets/89d0bd48-d74f-41e5-a411-23b9ed44d4f8)

**Comment by Onimaimai** [comment]
> 兄弟你在干嘛啊兄弟,
> 你加了config=Config, 就不要merge我PR的了啊
> ![S41020-18300917_com kiwibrowser browser](https://github.com/user-attachments/assets/89d0bd48-d74f-41e5-a411-23b9ed44d4f8)

我的我的，当成覆盖了🥲
