### ISSUE TITLE
ImportError: cannot import name 'main' from 'pip'

### ISSUE THREAD

**Issue by RiotGamesU** [nonebot/nonebot2#318]
```
Debian GNU/Linux 10 (buster)
Linux VM-0-7-debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
Python 3.7.3
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

root@adebian:~# nb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/handlers/_pip.py", line 4, in <module>
    from pip._internal.cli.main import main as pipmain
ModuleNotFoundError: No module named 'pip._internal.cli.main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nb", line 6, in <module>
    from nb_cli.__main__ import main
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/__init__.py", line 5, in <module>
    from nb_cli.commands.main import init, run
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/commands/main.py", line 4, in <module>
    from nb_cli.handlers import create_project, run_bot
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/handlers/__init__.py", line 9, in <module>
    from .project import create_project
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/handlers/project.py", line 7, in <module>
    from .adapter import _get_adapters
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/handlers/adapter.py", line 9, in <module>
    from ._pip import _call_pip_install, _call_pip_update
  File "/usr/local/lib/python3.7/dist-packages/nb_cli/handlers/_pip.py", line 6, in <module>
    from pip import main as pipmain
ImportError: cannot import name 'main' from 'pip' (/usr/lib/python3/dist-packages/pip/__init__.py)
```

**Comment by yanyongyu** [comment]
升级 `pip`

**Comment by RiotGamesU** [comment]
> 升级 `pip`

thanks
