### ISSUE TITLE
Bug: 无法正常解析回复中的 message 字段

### ISSUE THREAD

**Issue by StarHeartHunt** [nonebot/nonebot2#325]
**描述问题：**

无法正常解析回复中的 `message` 字段

**如何复现？**

1. 使用 go-cqhttp v1.0.0-beta2
2. 在任意群回复任意消息不删除 at

**期望的结果**

正常解析消息后执行 `matcher`

**环境信息：**

 - OS: CentOS Linux release 8.3.2011
 - Python Version: 3.8.3
 - Nonebot Version: 2.0.0a13.post1

**日志**
```python
04-12 11:40:07 [INFO] nonebot | CQHTTP 3403056756 | [message]: {'time': 1618198807, 'self_id': 3403056756, 'post_type': 'message', 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Paprika', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 947371563}, 'group_id': 960951162, 'message_seq': 1306, 'user_id': 947371563, 'message_id': 256427854, 'message_type': 'group', 'raw_message': '[CQ:reply,id=136643415][CQ:at,qq=3403056756] [CQ:at,qq=3403056756] test', 'font': 0, 'sub_type': 'normal', 'anonymous': None, 'message': [{'data': {'id': '136643415'}, 'type': 'reply'}, None, {'data': {'qq': '3403056756'}, 'type': 'at'}, {'data': {'text': ' '}, 'type': 'text'}, {'data': {'qq': '3403056756'}, 'type': 'at'}, {'data': {'text': ' test'}, 'type': 'text'}]}
04-12 11:40:07 [ERROR] nonebot | Failed to handle event. Raw: {'anonymous': None, 'font': 0, 'group_id': 960951162, 'message': [{'data': {'id': '136643415'}, 'type': 'reply'}, None, {'data': {'qq': '3403056756'}, 'type': 'at'}, {'data': {'text': ' '}, 'type': 'text'}, {'data': {'qq': '3403056756'}, 'type': 'at'}, {'data': {'text': ' test'}, 'type': 'text'}], 'message_id': 256427854, 'message_seq': 1306, 'message_type': 'group', 'post_type': 'message', 'raw_message': '[CQ:reply,id=136643415][CQ:at,qq=3403056756] [CQ:at,qq=3403056756] test', 'self_id': 3403056756, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Paprika', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 947371563}, 'sub_type': 'normal', 'time': 1618198807, 'user_id': 947371563}
Traceback (most recent call last):
  File "/usr/local/python3/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/cqhttp/bot.py", line 328, in handle_message
    await handle_event(self, event)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 222, in handle_event
    _, _ = TrieRule.get_value(bot, event, state)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/rule.py", line 139, in get_value
    message = event.get_message()
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/cqhttp/event.py", line 44, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
```

**Comment by StarHeartHunt** [comment]
go-cqhttp `v1.0.0-beta3` 版本修复了这个问题，可能是 `Array` 上报部分字段为 `null` 导致的
