### ISSUE TITLE
Bug: 某些事件上报时logger在着色时对tag存在错误解析

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/nonebot2#459]
**描述问题：**

在处理gocq协议端自身发送消息事件上报时，对自身发送的合并转发消息事件的logger在着色时，存在对tag的错误解析

**如何复现？**

1. 使用gocq协议端，启用report-self-message
2. 让bot发送合并转发消息

**期望的结果**

正常的log，没有异常

**环境信息：**

 - OS: Windows 10 21H1
 - Python Version: 3.9.6
 - Nonebot Version: 2.0.0a13.post1
 - gocq Version: 1.0.0-beta5

**日志**

gocq端

```
[2021-08-02 21:47:27] [INFO]: 收到群 xxxxxxx(1111111111) 内 aaaaa(987654321) 的消息: [CQ:forward,id=y9s194...." m_fileName="162790000..." tSum="3" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="1"><title color="#000000" size="34">群聊的聊天记录</title> <title size="26" color="#777777">aaaaa: [图片]</title><title size="26" color="#777777">aaaaa: [图片]</title><title size="26" color="#777777">aaaaa: [图片]</title><hr></hr><summary size="26" color="#808080">查看 3 条转 发消息</summary></item><source name="聊天记录]你的QQ暂不支持查看&#91;转发多条消息&#93;，请期待后续版本。 (-277626502)
```

nonebot端

```
Task exception was never retrieved
future: <Task finished name='Task-557' coro=<Bot.handle_message() done, defined at C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py:294> exception=ValueError('Closing tag "</title>" has no corresponding opening tag')>
Traceback (most recent call last):
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 329, in handle_message
    await handle_event(self, event)
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\nonebot\message.py", line 202, in handle_event
    logger.opt(colors=True).info(log_msg)
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_logger.py", line 1971, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_logger.py", line 1944, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_colorizer.py", line 369, in prepare_simple_message
    parser.feed(string)
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_colorizer.py", line 245, in feed
    raise ValueError('Closing tag "%s" has no corresponding opening tag' % markup)
ValueError: Closing tag "</title>" has no corresponding opening tag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 331, in handle_message
    logger.opt(colors=True, exception=e).error(
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_logger.py", line 1983, in error
    __self._log("ERROR", None, False, __self._options, __message, args, kwargs)
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_logger.py", line 1944, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_colorizer.py", line 369, in prepare_simple_message
    parser.feed(string)
  File "C:\Users\ailitonia\PycharmProjects\test\venv\lib\site-packages\loguru\_colorizer.py", line 245, in feed
    raise ValueError('Closing tag "%s" has no corresponding opening tag' % markup)
ValueError: Closing tag "</title>" has no corresponding opening tag
```

**Comment by yanyongyu** [comment]
该问题应该已经在dev修复

https://github.com/nonebot/nonebot2/commit/f42d578765f83021618edda292c451f75d537a43#diff-cc34594eea1f5c42384a0f1b64b4f75363d1e88e37f9418e11a20663adf21dbdL40-R40

**Comment by noear** [comment]
这是个什么问题啊？我的项目也现这个错。

```python
e_msg = traceback.format_exc()
log.warning(f"Client consume handle error, key={message.getKey()}, error: \n{e_msg}")
```

我是把 traceback.format_exc() 日志打印出这个错。。。如果没有它，又是好的

**Comment by yanyongyu** [comment]
@noear 请注意你的log是否开启了colorize，如果开启了需要转义tag标签，请参考[loguru文档](https://loguru.readthedocs.io/en/stable/api/logger.html#color)

**Comment by noear** [comment]
@yanyongyu  谢谢。。。我后面使用 “log = _logger.opt(colors=False)”，解决问题了。。。//当时，一头雾水
