### ISSUE TITLE
Feature: 支持Mirai-API-HTTP 2.x

### ISSUE THREAD

**Issue by zxz0415** [nonebot/nonebot2#470]
<img width="746" alt="截屏2021-08-05 下午5 55 03" src="https://user-images.githubusercontent.com/32358438/128331204-2de21bb1-1d0b-49c0-a124-03e4e19819b4.png">

**Comment by yanyongyu** [comment]
@mnixry

**Comment by mnixry** [comment]
由于mirai-api-http2改动较大, 我们很难不相应地作出一些破坏性的更改
所以对于mirai-api-http2的支持我们预计将在之后一段时间跟随大版本更新一同进行

**Comment by mnixry** [comment]
对2.0的正向WebSocket支持已经就绪, 可以参考[`feature/mirai-2.0-support`](https://github.com/nonebot/nonebot2/tree/feature/mirai-2.0-support)分支进行先行测试和使用

但是由于以下原因, 对`mirai-api-http 2.0`的适配将在短期内不会合入主分支:
  - 截至今日, `mirai-console-loader`能够自动下载的版本仍旧停留在`1.10.0`, 这意味着用户需要更多的配置和使用步骤
  - 由于2.0的设计问题, 我们目前无法进行对反向Websocket的适配

**Comment by ieew** [comment]
在使用 feature/mirai-2.0-support 分支的时候发现了一个奇怪的现象：
当我在插件中使用 `await bot.mute(target=群id, memberId=群内的某个用户的id, time=120)` api 时 mah2 返回了 `<ActionFailed code=5, msg= 指定对象不存在>`
当我使用 `await bot.quit(target=群id)` api 时 mah2 反应非常迅速——bot 光速退出了群聊天

已知使用禁言 api 时群内确实存在被禁言的用户，并且 bot 确实是管理员，被禁言用户也只是普通群员
已知我在 `http://www.jsons.cn/websocket/` 手动连接 mah2 并且手动构建 api 内容的情况下可以正常禁言需要被口球的群员

以下是报错的日志：
```log
01-05 15:13:07 [ERROR] nonebot | Running matcher <Matcher from event, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\nonebot\message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\nonebot\message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\nonebot\matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\nonebot\handler.py", line 64, in __call__
    await self.func(
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\vuvu\plugins\event\__init__.py", line 13, in _
    await bot.mute(target=601249169, memberId=1066328304, time=1)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\nonebot\adapters\_bot.py", line 172, in call_api
    raise exception
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\venv\lib\site-packages\nonebot\adapters\_bot.py", line 155, in call_api
    result = await self._call_api(api, **data)
  File "C:\Users\xxxxxxx\Desktop\git\nonebots\vuvu\.\adapters\mirai2\bot.py", line 169, in _call_api
    raise ActionFailed(**(result.get('data') or result))
adapters.mirai2.exception.ActionFailed: <ActionFailed code=5, msg=指定对象不存在>
```


api发送内容：
```json
{
  "syncId":"0",
  "command":"mute",
  "subcommand":null,
  "content":{
    "target":601249169,
    "memberId":643875312,
    "time":1
  }
}
```

mah2返回内容：
```json
{
  "syncId":"0",
  "data":{
    "code":5,
    "msg":"指定对象不存在"
  }
}
```

测试插件代码：
```python3
# import nonebot
from nonebot import get_driver
from nonebot import on_command
from nonebot.adapters import Bot, Event


global_config = get_driver().config
command = on_command("测试", priority=5)

@command.handle()
async def _(bot: Bot, event: Event):
    await bot.mute(target=123456789, memberId=1234567890, time=1)
    #await bot.quit(target=123456789)
```

我的 pip list：
```log
Package                    Version
-------------------------- -----------
aiofiles                   0.7.0
aiohttp                    3.8.1
aiosignal                  1.2.0
anyio                      3.4.0
APScheduler                3.8.1
arrow                      1.2.1
asgiref                    3.4.1
async-timeout              4.0.2
attrs                      21.4.0
binaryornot                0.4.4
certifi                    2021.10.8
chardet                    4.0.0
charset-normalizer         2.0.9
click                      8.0.3
colorama                   0.4.4
cookiecutter               1.7.3
fastapi                    0.68.2
frozenlist                 1.2.0
h11                        0.12.0
h2                         4.1.0
hpack                      4.0.0
httpcore                   0.14.3
httptools                  0.2.0
httpx                      0.21.1
hyperframe                 6.0.1
idna                       3.3
Jinja2                     3.0.3
jinja2-time                0.2.0
loguru                     0.5.3
MarkupSafe                 2.0.1
multidict                  5.2.0
nb-cli                     0.5.1
nonebot-plugin-apscheduler 0.1.2
nonebot2                   2.0.0a16
pip                        21.3.1
poyo                       0.5.0
prompt-toolkit             3.0.24
pydantic                   1.8.2
pyfiglet                   0.8.post1
pygtrie                    2.4.2
python-dateutil            2.8.2
python-dotenv              0.19.2
python-engineio            3.14.2
python-slugify             5.0.2
python-socketio            4.6.1
pytz                       2021.3
pytz-deprecation-shim      0.1.0.post0
PyYAML                     6.0
requests                   2.27.0
rfc3986                    1.5.0
setuptools                 57.4.0
six                        1.16.0
sniffio                    1.2.0
starlette                  0.14.2
text-unidecode             1.3
tomlkit                    0.7.2
typing_extensions          4.0.1
tzdata                     2021.5
tzlocal                    4.1
urllib3                    1.26.7
uvicorn                    0.15.0
watchgod                   0.7
wcwidth                    0.2.5
websockets                 10.1
win32-setctime             1.0.4
yapf                       0.32.0
yarl                       1.7.2
```

**Comment by mnixry** [comment]
> 当我在插件中使用 `await bot.mute(target=群id, memberId=群内的某个用户的id, time=120)` api 时 mah2 返回了 `<ActionFailed code=5, msg= 指定对象不存在>`

@ieew 为了符合PEP8命名规范，我对所有字段做了转换，将camelCase改为snake_case 
你可能已经在事件字段的命名上见到了这一点
举例来说，你可能需要使用`member_id`来替换`memberId`

**Comment by ieew** [comment]
> > 当我在插件中使用 `await bot.mute(target=群id, memberId=群内的某个用户的id, time=120)` api 时 mah2 返回了 `<ActionFailed code=5, msg= 指定对象不存在>`
> 
> @ieew 为了符合PEP8命名规范，我对所有字段做了转换，将camelCase改为snake_case 你可能已经在事件字段的命名上见到了这一点 举例来说，你可能需要使用`member_id`来替换`memberId`

感谢解答，我尝试了一下，确实如此
