### ISSUE TITLE
Bug: event.dict() 方法异常

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/nonebot2#473]
**描述问题：**

使用 event.dict() 方法报错

**如何复现？**

编写测试插件

```python
from nonebot.typing import T_State
from nonebot.plugin import on_message
from nonebot.matcher import Matcher
from nonebot.adapters.cqhttp.event import Event
from nonebot.adapters.cqhttp.bot import Bot
from nonebot.message import run_preprocessor


test = on_message()


@run_preprocessor
async def handle_run_preprocessor(matcher: Matcher, bot: Bot, event: Event, state: T_State):
    print(event.dict())
```

**期望的结果**

正常输出

**环境信息：**

 - OS: Windows 10 21H1
 - Python Version: 3.9.6
 - Nonebot Version: 2.0.0a14

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: 1.0.0-beta5

**截图或日志**

```python
Traceback (most recent call last):
  File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\venv\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\venv\lib\site-packages\nonebot\message.py", line 139, in _run_matcher
    await asyncio.gather(*coros)
  File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\omega_miya\utils\test.py", line 24, in handle_run_preprocessor
    print('event dict', event.dict())
  File "pydantic\main.py", line 510, in pydantic.main.BaseModel.dict
    return dict(
  File "pydantic\main.py", line 875, in _iter
    v = self._get_value(
  File "pydantic\main.py", line 816, in pydantic.main.BaseModel._get_value
    return v.__class__(*seq_args) if is_namedtuple(v.__class__) else v.__class__(seq_args)
  File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\venv\lib\site-packages\nonebot\adapters\_base.py", line 330, in __init__
    self.extend(self._construct(message))
  File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\venv\lib\site-packages\nonebot\adapters\_base.py", line 400, in extend
    for segment in obj:
  File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\venv\lib\site-packages\nonebot\adapters\cqhttp\message.py", line 265, in _construct
    yield MessageSegment(seg["type"], seg.get("data") or {})
  File "C:\Users\ailitonia\PycharmProjects\nonebot2_miya\venv\lib\site-packages\nonebot\adapters\_base.py", line 278, in __getitem__
    return self.data[key]
KeyError: 'type'
```

**其他**

https://github.com/nonebot/nonebot2/blob/916d620012a189669ed3a0231811305e76a2eef2/nonebot/adapters/_base.py#L287-L288

https://github.com/nonebot/nonebot2/blob/832875e7cfb76e69a8cc06c7ca2c97208f4a8a58/nonebot/adapters/_base.py#L277-L278

cqhttp-adapter 似乎没有根据 MessageSegment 基类更新自己的解析方法

（或者 MessageSegment 基类魔法方法更新也需要考虑 adapter 兼容？）

**Comment by mnixry** [comment]
已经在https://github.com/nonebot/nonebot2/commit/3564228183047906045fe56d352808798b6bae40 和 https://github.com/nonebot/nonebot2/commit/8e97a84ad87beacbee2a36eebbe541760d9e510f 中修复, 将会在下个版本发布
