### ISSUE TITLE
Unexpected exception occurred while websocket loop.

### ISSUE THREAD

**Issue by Redbeanw44602** [nonebot/nonebot2#486]
**描述问题：**

无法启动Nonebot

**如何复现？**

使用MiraiHttp协议启动Nonebot

**期望的结果**

正确启动

**环境信息：**

 - OS: Windows 11, Java 11
 - Python Version: 3.9.6
 - Nonebot Version: v2.0.0a14

**协议端信息：**

 - 协议端: mirai-http
 - 协议端版本: v2.2.0

**截图或日志**

启动日志
```
08-10 16:23:17 [SUCCESS] nonebot | NoneBot is initializing...
08-10 16:23:17 [INFO] nonebot | Current Env: dev
08-10 16:23:17 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('0.0.0.0'), 'port': 1146, 'debug': True, 'log_level': None, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': {'xxx'}, 'nickname': {'xxx'}, 'command_start': {'', '/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'mirai_port': 1145, 'mirai_auth_key': 'xxx', 'custom_config': 'common config', 'environment': 'dev', 'mirai_host': '127.0.0.1'}
08-10 16:23:17 [DEBUG] nonebot | Succeeded to load adapter "mirai"
08-10 16:23:17 [SUCCESS] nonebot | Running NoneBot...
08-10 16:23:17 [DEBUG] nonebot | Loaded adapters: mirai
08-10 16:23:17 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:1146 (Press CTRL+C to quit)
08-10 16:23:17 [INFO] uvicorn | Started reloader process [6148] using watchgod
08-10 16:23:18 [SUCCESS] nonebot | NoneBot is initializing...
08-10 16:23:18 [INFO] nonebot | Current Env: dev
08-10 16:23:18 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('0.0.0.0'), 'port': 1146, 'debug': True, 'log_level': None, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': {'xxx'}, 'nickname': {'xxx'}, 'command_start': {'', '/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'mirai_port': 1145, 'mirai_host': '127.0.0.1', 'mirai_auth_key': 'xxx', 'environment': 'dev', 'custom_config': 'common config'}
08-10 16:23:18 [DEBUG] nonebot | Succeeded to load adapter "mirai"
08-10 16:23:18 [INFO] uvicorn | Started server process [9380]
08-10 16:23:18 [INFO] uvicorn | Waiting for application startup.
08-10 16:23:18 [INFO] uvicorn | Application startup complete.
08-10 16:23:18 [ERROR] nonebot | Unexpected exception occurred while websocket loop
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\uvicorn\server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 407, in _ws_loop
    setup_ = await setup()
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\nonebot\adapters\mirai\bot.py", line 211, in url_factory
    session = await SessionManager.new(
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\nonebot\adapters\mirai\bot.py", line 119, in new
    response.raise_for_status()
  File "c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\httpx\_models.py", line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 404 Client Error: Not Found for url: http://127.0.0.1:1145/auth
For more information check: https://httpstatuses.com/404
c:\users\redbeanw\appdata\local\programs\python\python39\lib\site-packages\httpx\_client.py:1978: UserWarning: Unclosed <httpx.AsyncClient object at 0x0000023533FF0F10>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
  warnings.warn(
08-10 16:23:23 [INFO] uvicorn | Shutting down
08-10 16:23:24 [INFO] uvicorn | Waiting for application shutdown.
08-10 16:23:24 [INFO] uvicorn | Application shutdown complete.
08-10 16:23:24 [INFO] uvicorn | Finished server process [9380]
08-10 16:23:24 [INFO] uvicorn | Stopping reloader process [6148]
```
env文件
```
# .env
ENVIRONMENT=dev
CUSTOM_CONFIG=common config  # 这个配置项在任何环境中都会被加载
```
env.dev文件
```
HOST=0.0.0.0  # 配置 NoneBot 监听的 IP/主机名
PORT=1146  # 配置 NoneBot 监听的端口
DEBUG=true  # 开启 debug 模式 **请勿在生产环境开启**
SUPERUSERS=["xxx"]  # 配置 NoneBot 超级用户
NICKNAME=["xxx"]  # 配置机器人的昵称
COMMAND_START=["/", ""]  # 配置命令起始字符
COMMAND_SEP=["."]  # 配置命令分割字符

MIRAI_AUTH_KEY=xxx
MIRAI_HOST=127.0.0.1 # 当MAH运行在本机时
MIRAI_PORT=1145 # MAH的监听端口
```
mirai-http配置文件
```
adapters: 
  - ws
debug: false
enableVerify: true
verifyKey: xxx
singleMode: false
cacheSize: 4096
adapterSettings:
  ws:
    ## websocket server 监听的本地地址
    ## 一般为 localhost 即可, 如果多网卡等情况，自定设置
    host: 127.0.0.1

    ## websocket server 监听的端口
    ## 与 http server 可以重复, 由于协议与路径不同, 不会产生冲突
    port: 1145

    ## websocket 用于消息同步的字段为 syncId, 一般值为请求时的原值，用于同步一次请求与响应
    ## 对于由 websocket server 主动发出的通知, 固定使用一个 syncId, 默认为 ”-1“
    reservedSyncId: -1
```
bot.py
```
import nonebot
from nonebot.adapters.mirai import Bot

nonebot.init()

driver = nonebot.get_driver()
driver.register_adapter("mirai", Bot, qq=xxx) # 注册 CQHTTP 的 Adapter

app = nonebot.get_asgi()

if __name__ == "__main__":
    nonebot.run()
```
本人按照文档中的步骤尝试多次无果，恳请大佬帮忙解决一下问题🤦‍♂️

**Comment by yanyongyu** [comment]
mah现在不支持2.0版本。duplicate of #470

**Comment by Redbeanw44602** [comment]
感谢
