### ISSUE TITLE
Bug: 不能从list[MessageSegment]构造Message

### ISSUE THREAD

**Issue by rmuchan** [nonebot/nonebot2#488]
**描述问题：**

以MessageSegment的列表为参数构造Message时发生异常：

```
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    Message([MessageSegment.text("1")])
  File "venv/lib/python3.9/site-packages/nonebot/adapters/_base.py", line 330, in __init__
    self.extend(self._construct(message))
  File "venv/lib/python3.9/site-packages/nonebot/adapters/_base.py", line 400, in extend
    for segment in obj:
  File "venv/lib/python3.9/site-packages/nonebot/adapters/cqhttp/message.py", line 265, in _construct
    yield MessageSegment(seg["type"], seg.get("data") or {})
  File "venv/lib/python3.9/site-packages/nonebot/adapters/_base.py", line 278, in __getitem__
    return self.data[key]
KeyError: 'type'
```

**如何复现？**

```python
from nonebot.adapters.cqhttp import Message, MessageSegment
Message([MessageSegment.text("1")])
```

**期望的结果**

得到`Message("1")`

**环境信息：**

 - OS: mac
 - Python Version: 3.9
 - Nonebot Version: 2.0.0a14

**Comment by mnixry** [comment]
Duplicate of #473
