### ISSUE TITLE
Question: 示例的dockerfile compose失败

### ISSUE THREAD

**Issue by KafCoppelia** [nonebot/nonebot2#643]
**描述问题：**

这个机器人自己通过`nb run`有一阵子，也加入了一些插件。现在想使用示例的dockerfile在docker中运行，但是compose失败，详情见下。

**如何复现？**

1. 进入bot.py所在根目录
2. `docker-compose up`

**期望的结果**

docker构建成功

**环境信息：**

 - OS: Ubuntu 20.04
 - Python Version: 3.9.7 64-bit
 - Nonebot Version: 2.0.0a16

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: 1.0.0-beta8-fix2

**截图或日志**
```
nonebot_1  | Checking for script in /app/prestart.sh
nonebot_1  | There is no script /app/prestart.sh
nonebot_1  | [2021-12-27 18:49:42 +0800] [1] [INFO] Starting gunicorn 20.1.0
nonebot_1  | [2021-12-27 18:49:42 +0800] [1] [INFO] Listening at: http://127.0.0.1:8080 (1)
nonebot_1  | [2021-12-27 18:49:42 +0800] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
nonebot_1  | [2021-12-27 18:49:42 +0800] [7] [INFO] Booting worker with pid: 7
nonebot_1  | [2021-12-27 18:49:43 +0800] [7] [ERROR] Exception in worker process
nonebot_1  | Traceback (most recent call last):
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
nonebot_1  |     worker.init_process()
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/workers.py", line 66, in init_process
nonebot_1  |     super(UvicornWorker, self).init_process()
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
nonebot_1  |     self.load_wsgi()
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
nonebot_1  |     self.wsgi = self.app.wsgi()
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
nonebot_1  |     self.callable = self.load()
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
nonebot_1  |     return self.load_wsgiapp()
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
nonebot_1  |     return util.import_app(self.app_uri)
nonebot_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
nonebot_1  |     mod = importlib.import_module(module)
nonebot_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
nonebot_1  |     return _bootstrap._gcd_import(name[level:], package, level)
nonebot_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
nonebot_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
nonebot_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
nonebot_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
nonebot_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
nonebot_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
nonebot_1  |   File "/app/bot.py", line 5, in <module>
nonebot_1  |     from nonebot.adapters.cqhttp import Bot as CQHTTPBot
nonebot_1  | ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'
nonebot_1  | [2021-12-27 18:49:43 +0800] [7] [INFO] Worker exiting (pid: 7)
nonebot_1  | {"loglevel": "info", "workers": 1, "bind": "127.0.0.1:8080", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": 1, "host": "127.0.0.1", "port": "8080"}
nonebot_1  | [2021-12-27 18:49:43 +0800] [1] [INFO] Shutting down: Master
nonebot_1  | [2021-12-27 18:49:43 +0800] [1] [INFO] Reason: Worker failed to boot.
nonebot_1  | {"loglevel": "info", "workers": 1, "bind": "127.0.0.1:8080", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": 1, "host": "127.0.0.1", "port": "8080"}
aquabot_nonebot_1 exited with code 3
```

**Comment by yanyongyu** [comment]
请在pyproject.toml中正确添加依赖

**Comment by KafCoppelia** [comment]
目前`nb run`运行机器人，机器人在初始化阶段没有任何报错，`pyproject.toml`如下：
[tool.poetry]
name = "AQUABOT"
version = "0.2.1"
description = "AQUABOT"
authors = ["KafCoppelia"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0.a1"

[tool.poetry.dev-dependencies]
nb-cli = "^0.5.0"
nonebot-plugin-test = "^0.3.0"

[nonebot.plugins]
# "nonebot_plugin_twitter"
# "nonebot_plugin_heisi"
plugins = [ "nonebot_plugin_apscheduler", "haruka_bot", 
            "nonebot_plugin_youthstudy", "nonebot_plugin_gamedraw", 
            "nonebot_plugin_heweather", "nonebot_plugin_web", 
            "nonebot_plugin_withdraw", "nonebot_plugin_test", 
            "nonebot_plugin_wordbank", "nonebot_plugin_analysis_bilibili",
            "nonebot_bison"]

plugin_dirs = ["src/plugins"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
在docker compose报错中主要是`ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'`这个错误，理解不能

**Comment by j1g5awi** [comment]
很明显你并没有在 pyproject.toml 中正确填写依赖，你之前使用 `nb run` 能够运行的原因是你没有使用 poetry 构建的虚拟环境。

**Comment by KafCoppelia** [comment]
已添加，添加后从头重新poetry配置虚拟环境后，使用Dockerfile build后可以构建container，似乎可以run起来。但若使用docker-compose up报错仍同上。

**Comment by yanyongyu** [comment]
docker-compose up --build

**Comment by yanyongyu** [comment]
如果还有问题欢迎到discussion.nonebot.dev提问

**Comment by KafCoppelia** [comment]
OK
