### ISSUE TITLE
Question: 启动Bot报错

### ISSUE THREAD

**Issue by zyp123456789** [nonebot/nonebot2#731]
**描述问题：**

无法启动bot

```python
C:\Users\Administrator\Desktop\bot\zxmbot>.\bot.py
01-24 03:29:22 [SUCCESS] nonebot | NoneBot is initializing...
01-24 03:29:22 [INFO] nonebot | Current Env: dev
01-24 03:29:22 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 2333, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev'}
01-24 03:29:23 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\zxmbot\bot.py", line 23, in <module>
    driver.register_adapter(MIRAI2Adapter)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\__init__.py", line 111, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\mirai2\adapter.py", line 35, in __init__
    self.mirai_config: Config = Config(**self.config.dict())
  File "pydantic\main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for Config
mirai_host
  field required (type=value_error.missing)
mirai_port
  field required (type=value_error.missing)
mirai_qq
  field required (type=value_error.missing)

C:\Users\Administrator\Desktop\bot\zxmbot>
```

**期望的结果**

**环境信息：**

 - OS: [Windows 10 x64]
 - Python Version: [python-3.9.8-amd64]
 - Nonebot Version: [今天用pip安装的最新版本]

**协议端信息：**

 - 协议端: [e.g. go-cqhttp]
 - 协议端版本: [e.g. 1.0.0]

**截图或日志**

![4A3B87DA-EC67-4AAB-8756-1F18897297A6](https://user-images.githubusercontent.com/27912639/150695073-607b7564-a632-406f-a8ae-25116880ec19.png)

**Comment by StarHeartHunt** [comment]
缺少 adapter 要求的相关配置，在对应的 .env 文件中给定 `mirai_host` `mirai_port` 和 `mirai_qq` 的值。
