### ISSUE TITLE
Bug: Message.template format 问题

### ISSUE THREAD

**Issue by kexue-z** [nonebot/nonebot2#770]
**描述问题：**

无法使用format

**如何复现？**

```py
from nonebot.adapters.onebot.v11 import Message
file_list = [
    "file:///file1.image",
    "file:///file2.image",
    ...
]
text = "img1:  {:image} img2: {:image} ..."

msg = Message.template(text).format(*file_list)
```

**期望的结果**

`msg` 为可以直接发送的 包含文字和图片的消息

**环境信息：**

 - OS: Linux CentOS8
 - Python Version: 3.9
 - Nonebot Version: 2.0.0-beta.1

**截图或日志**
```log
Traceback (most recent call last):
  File "/data/nb-test/test/re_test.py", line 23, in <module>
    msg = Message.template(text).format(*file_list)
  File "/root/.cache/pypoetry/virtualenvs/nb-test-NOSw4fD6-py3.9/lib/python3.9/site-packages/nonebot/adapters/_template.py", line 80, in format
    msg += self.vformat(self.template, args, kwargs)
  File "/root/.cache/pypoetry/virtualenvs/nb-test-NOSw4fD6-py3.9/lib/python3.9/site-packages/nonebot/adapters/_template.py", line 94, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/root/.cache/pypoetry/virtualenvs/nb-test-NOSw4fD6-py3.9/lib/python3.9/site-packages/nonebot/adapters/_template.py", line 165, in _vformat
    formatted_text = self.format_field(obj, str(format_control))
  File "/root/.cache/pypoetry/virtualenvs/nb-test-NOSw4fD6-py3.9/lib/python3.9/site-packages/nonebot/adapters/_template.py", line 181, in format_field
    super().format_field(value, format_spec)
  File "/root/miniconda3/lib/python3.9/string.py", line 235, in format_field
    return format(value, format_spec)
ValueError: Invalid format specifier
```

**Comment by yanyongyu** [comment]
fixed in #772
