### ISSUE TITLE
Bug: 不能加载自建插件

### ISSUE THREAD

**Issue by miangou** [nonebot/nonebot2#827]
**描述问题：**

nb run不能正确载入自建插件

**如何复现？**

nb run
**期望的结果**

加载成功

**环境信息：**

 - OS: Windows10
 - Python Version: 3.10.1
 - Nonebot Version: 2.0b2

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: 1.0.0 

**截图或日志**

```python
02-20 19:30:23 [ERROR] nonebot | Failed to import "jrrp"
Traceback (most recent call last):
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Natsumi\Downloads\bot\test\.\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 71, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 110, in load_all_plugins
    return set(
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 111, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 96, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.plugins'
02-20 19:30:28 [ERROR] nonebot | Failed to import "jrrp"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 76, in serve
    config.load()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Natsumi\Downloads\bot\test\.\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 71, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 110, in load_all_plugins
    return set(
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 111, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 96, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Natsumi\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.plugins'
```

**Comment by miangou** [comment]
[复现目录_2.zip](https://github.com/nonebot/nonebot2/files/8104087/_2.zip)

**Comment by CherryGS** [comment]
你本地python环境是不是有名为test的包 , 请更换文件夹名字然后试一试

**Comment by yanyongyu** [comment]
由于太久没有得到回复，先close了issue，如果有问题欢迎再open
