### ISSUE TITLE
Bug: 群信息右键回复似乎导致会报错 Failed to handle event

### ISSUE THREAD

**Issue by DeSireFire** [nonebot/nonebot2#89]
**描述问题：**

提示报错 Failed to handle event.
使用的go-cqhttp+nb
第一次部署nb2,按照文档"创建一个完整项目"->python bot.py
报错信息：
```text
11-28 15:56:53 [ERROR] nonebot | Failed to handle event. Raw: {'anonymous': None, 'font': 0, 'group_id': 91*55, 'message': [MessageSegment(type='reply', data={'id': '-10*721'})
, MessageSegment(type='at', data={'qq': '69*5'}), MessageSegment(type='text', data={'text': ' 我只看过脸遮住的'})], 'message_id': 88*154, 'message_type': 'group', 'post_type':
'message', 'raw_message': '[CQ:reply,id=-10*21][CQ:at,qq=6*25] 我只看过脸遮住的', 'self_id': 14*49, 'sender': {'age': 0, 'area': '', 'card': '阿尔托莉雅·草履虫·潘德拉
贡', 'level': '', 'nickname': '草履虫', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 11*14}, 'sub_type': 'normal', 'time': 1606550213, 'user_id': 11*14}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Python\Python37\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "E:\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "E:\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "E:\Python\Python37\lib\asyncio\base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "E:\Python\Python37\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "E:\Python\Python37\lib\asyncio\base_events.py", line 1786, in _run_once
    handle._run()
  File "E:\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
> File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 354, in handle_message
    await _check_reply(self, event)
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 114, in _check_reply
    event.reply = await bot.get_msg(message_id=msg_seg.data["id"])
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 402, in call_api
    seq, self.config.api_timeout))
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 230, in _handle_api_result
    raise ActionFailed(retcode=result.get("retcode"))
nonebot.exception.ActionFailed: <ActionFailed, retcode=100>

11-28 15:56:54 [INFO] nonebot | CQHTTP | 1486431349 [message.group.normal]: Message -1378210328 from 1147259114@[群:91*55]: "[CQ:image,file=0b06c834f89cc95bbc7d2c882c2f5382.image,u
rl=http://gchat.qpic.cn/gchatpic_new/1147259114/910883855-2764891748-0B06C834F89CC95BBC7D2C882C2F5382/0?term=2]"
11-28 15:56:56 [DEBUG] nonebot | CQHTTP | Calling API get_msg
11-28 15:56:56 [ERROR] nonebot | Failed to handle event. Raw: {'anonymous': None, 'font': 0, 'group_id': 91*55, 'message': [MessageSegment(type='reply', data={'id': '11*85'}),
 MessageSegment(type='at', data={'qq': '25*94'}), MessageSegment(type='text', data={'text': ' '}), MessageSegment(type='at', data={'qq': '2508512894'}), MessageSegment(type='text'
, data={'text': ' 闪图吗'})], 'message_id': -623043202, 'message_type': 'group', 'post_type': 'message', 'raw_message': '[CQ:reply,id=1153009885][CQ:at,qq=25*94] [CQ:at,qq=2*12
894] 闪图吗', 'self_id': 14*49, 'sender': {'age': 0, 'area': '', 'card': '喵喵定制 香草蛋仔_', 'level': '', 'nickname': '星野_', 'role': 'member', 'sex': 'unknown', 'title': '', '
user_id': 240714778}, 'sub_type': 'normal', 'time': 1606550216, 'user_id': 240714778}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Python\Python37\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "E:\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "E:\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "E:\Python\Python37\lib\asyncio\base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "E:\Python\Python37\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "E:\Python\Python37\lib\asyncio\base_events.py", line 1786, in _run_once
    handle._run()
  File "E:\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
> File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 354, in handle_message
    await _check_reply(self, event)
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 114, in _check_reply
    event.reply = await bot.get_msg(message_id=msg_seg.data["id"])
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 402, in call_api
    seq, self.config.api_timeout))
  File "D:\ProgramData\pyVenvs\nyamoo\lib\site-packages\nonebot\adapters\cqhttp\__init__.py", line 230, in _handle_api_result
    raise ActionFailed(retcode=result.get("retcode"))
nonebot.exception.ActionFailed: <ActionFailed, retcode=100>

```

**如何复现？**

1. 群聊天对某人右键选择回复信息，似乎就会导致这个问题。
2. 下面发出截图，跟报错信息一一对应。

**期望的结果**

虽然不会影响到整体运行，但是想知道如何处理这样的错误，不知道切入点.
总之先反馈一下。

**环境信息：**

 - OS: win10 2004 企业G
 - Python Version: 3.77
 - Nonebot Version: nonebot2 V2.0.0a6

**截图**

![image](https://user-images.githubusercontent.com/18726905/100497521-fd551880-3196-11eb-8709-97dca2c67d8e.png)

![image](https://user-images.githubusercontent.com/18726905/100497562-3bead300-3197-11eb-8bff-4bdbfa68868b.png)

**Comment by he0119** [comment]
这个 <ActionFailed, retcode=100>，是 API 调用失败报错。错误大概应该去 go-cqhttp 上找。

**Comment by yanyongyu** [comment]
这个问题应该查看gocq的日志报错具体原因

**Comment by DeSireFire** [comment]
好的！感谢，我去gocq那边反馈一下233.
