### ISSUE TITLE
Bug: Union Checking Failed

### ISSUE THREAD

**Issue by forchannot** [nonebot/nonebot2#998]
**描述问题：**

这个插件中有一个语音相关功能，beta3版本会报错，但是beta2版本不会。不清楚是插件没有适配还是beta3的bug，来问一下。其他命令没有问题

**如何复现？**

输入littlepaimon插件对应的语音，beta2版本能够成功发生语音，beta3会报一大堆错，日志在下面
**期望的结果**

正常发送语音

**环境信息：**

 - OS: [windows]
 - Python Version: [3.9.1]
 - Nonebot Version: [nonebot2的beta3]

**协议端信息：**

 - 协议端: [go-cqhttp]
 - 协议端版本: [1.0.0-rc1]

**截图或日志**

```python
05-21 20:51:30 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.Guess_voice, type=message, priority=12, temp=False>
05-21 20:51:30 [INFO] nonebot | Matcher <Matcher from LittlePaimon.Guess_voice, type=message, priority=12, temp=False> running complete
05-21 20:51:30 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.Guess_voice, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\nonebot\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 89, in __call__
    values = await self.solve(**kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 188, in solve
    await checker._solve(**params)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\params.py", line 208, in _solve
    if isinstance(event, field.type_):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\typing.py", line 697, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\typing.py", line 700, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

**Comment by MingxuanGame** [comment]
Union 出现了问题

Related https://github.com/KimigaiiWuyi/GenshinUID/issues/236

**Comment by forchannot** [comment]
> Union 出现了问题
> 
> Related [KimigaiiWuyi/GenshinUID#236](https://github.com/KimigaiiWuyi/GenshinUID/issues/236)

那要怎么解决呢

**Comment by yanyongyu** [comment]
暂时可以通过使用python 3.10解决

**Comment by forchannot** [comment]
> 暂时可以通过使用python 3.10解决

好像并没有修复啊，还是报错，用pip升级了nonebot了，是更新还没有提交到python包吗。而且升级过程中遇到了这个
![image](https://user-images.githubusercontent.com/100580891/169694606-c72fd5ee-292f-4e5e-ba1e-914d15b808f9.png)
![image](https://user-images.githubusercontent.com/100580891/169694608-b959e45d-fd7e-4d25-a118-51a3159292db.png)
这个tomlkit包一个要高版本一个要低版本

**Comment by yanyongyu** [comment]
修复已经合并到master分支，但并未发布到pypi。你可以选择安装master分支代码

**Comment by forchannot** [comment]
> 修复已经合并到master分支，但并未发布到pypi。你可以选择安装master分支代码

那我等一下发步到pypi吧。现在也能用，主要是不想折腾
